### ISSUE TITLE
concerning ungoogled-chromium-xdg 

### ISSUE THREAD

**Issue by noahvogt** [arenekosreal/QDamakuEngine#6]
Hi, I am the maintainer of [ungoogled-chromium-xdg](https://aur.archlinux.org/packages/ungoogled-chromium-xdg) and am writing you here because I have not found another way to contact you (You have hidden your email address in your AUR and github account, even your git commits point to the noreply email of github.) 

I want to first thank you for your usual commitment and help you provided to ungoogled-chromium-xdg by flagging the package out-of-date if it is actually out-of-date and even opening [a pull request](https://github.com/noahvogt/ungoogled-chromium-xdg-aur/pull/3) on my github this summer. 

You flagged ungoogled-chromium-xdg out of date 5 hours ago. But why do I write to you?

From your comment "159 has been released and I think you may need to update the PKGBUILD to use this instead 123 version." I think you meant I should update the source for to ungoogled chromium changes to the newer version. But actually if you look [at the changes between .119.0.6045.123-1 and 119.0.6045.159-1](https://github.com/ungoogled-software/ungoogled-chromium/commit/0461ff207b3c4c66cd31f82fb92a08e2021f1bf8). As you can see in the commit, the only thing that changes is only the line numbering in a patch file. Hence EVEN IF you would update the ungoogled chromium release to 119.0.6045.159-1, it would PRODUCE EXACTLY THE SAME BINARY as with 119.0.6045.123-1. I don't want to trigger a rebuild for people that is completely unnecessary.

But why do I do it that way? Because ungoogled chromium releases lag behind chromium releases (both official and the arch extra repository) some days, I try to speed that up by looking at the Pull Request that sits idle for some days in the ungoogled chromium repository waiting to be merged and released. This is why ungoogled-chromium-xdg is often more up-to-date than ungoogled-chromium. Even as of writing this is true, see the image below:

![Screenshot_20231117-140521_gnome](https://github.com/zhanghua000/QDamakuEngine/assets/64090814/9190e9fc-0f0d-4ebd-9d5b-c592c6a248b8)

So please check if it is really needed to update the ungoogled chromium release before flagging this package up to date. Hopefully my explanation has been somewhat understandable. If it is not clear, do not hesitate to contact me. And since you don't seem to want to expose you email address to the public, please just write me directly to <noah@noahvogt.com> so I can contact you better (and we can privatly exchange emails that way). I also have matrix and signal and other more private ways of messaging if you prefer that.

**Comment by arenekosreal** [comment]
Ah, I understand that after your explanation, I feel sorry about my carelessness, I just checked the tag simply rather than checked the actual code changes.  I will check more carefully in the future to prevent this happen again. Sorry for the inconvenience resulted by my rude behavior. You can email me to zhanghuadedn@gmail.com in the future once there is required to do so.
